import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Button from "@/components/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Step02-Linking & Navigation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Button />
        {children}
        <Footer />
      </body>
    </html>
  );
}
